spring.application.name=FamilyTree

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.messages.encoding=UTF-8
spring.profiles.default=dev
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

server.port=8080

app.admin.username=
app.admin.password=
app.dev-user.username=
app.dev-user.password=
app.lineage.default-last-name=
app.lineage.default-gender=
app.names.backfill-missing-nepali-on-startup=false
