name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, familytree-prod]

    steps:
      - name: Run deploy script
        run: |
          bash /home/yuva/deploy-familytree.sh
